input {
  file {
    id => "snort_json"
    path => ["/alerts/alert_json.txt"]
    start_position => "beginning"
    sincedb_path => "/usr/share/logstash/data/snort.sincedb"
    codec => json
  }
}

filter {
  date {
    match => ["seconds", "UNIX"]
    target => "@timestamp"
  }

  mutate {
    rename => {
      "src_addr" => "[source][ip]"
      "src_port" => "[source][port]"
      "dst_addr" => "[destination][ip]"
      "dst_port" => "[destination][port]"
      "proto" => "[network][transport]"
      "sid" => "[rule][id]"
      "msg" => "[rule][description]"
      "class" => "[rule][category]"
      "priority" => "[event][severity]"
      "iface" => "[observer][ingress][interface][name]"
    }
    convert => {
      "[source][port]" => "integer"
      "[destination][port]" => "integer"
      "[event][severity]" => "integer"
      "pkt_len" => "integer"
    }
    lowercase => ["[network][transport]"]
    add_field => {
      "[event][kind]" => "alert"
      "[event][category]" => "intrusion_detection"
      "[observer][type]" => "ids"
      "[observer][vendor]" => "Cisco"
      "[observer][product]" => "Snort"
      "[labels][lab]" => "network-forensics-lab"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "snort-alerts-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
