input {
  file {
    id => "normalised_ids_json"
    path => ["/alerts/normalized-alerts.jsonl"]
    mode => "read"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => json
  }
}

filter {
  mutate {
    add_field => {
      "[labels][lab]" => "network-forensics-lab"
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "ids-alerts-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
